[package]
name = "flight_booking"
type = "bin"
authors = [""]

[dependencies]
sha256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/sha256" }
noir_rsa = { tag = "v0.7.0", git = "https://github.com/noir-lang/noir_rsa" }
bignum = { tag = "v0.6.1", git = "https://github.com/noir-lang/noir-bignum" }